import {
  IconHome,
  IconChalkboard,
  IconBuildingBank,
  IconBriefcase,
  IconShield,
  IconBulb,
  IconFlask,
  IconChartBar,
  IconBraces,
  IconFileAnalytics,
  IconMessageCircle,
  IconUsersGroup,
  IconUser,
  IconRobot,
  IconTools,
  IconUsers,
  IconClipboardList,
  IconBook,
  IconCalendar,
  IconSchool,
  IconSettings,
  IconStethoscope,
  IconChartPie,
  IconBooks,
  IconCalendarEvent,
  IconBuilding,
  IconAdjustments,
  IconSchoolBell,
  IconFirstAidKit,
  IconPresentation,
} from '@tabler/icons-react';

export const iconMap = {
  IconHome,
  IconChalkboard,
  IconBuildingBank,
  IconBriefcase,
  IconShield,
  IconBulb,
  IconFlask,
  IconChartBar,
  IconBraces,
  IconFileAnalytics,
  IconMessageCircle,
  IconUsersGroup,
  IconUser,
  IconRobot,
  IconTools,
  // Better icons for navigation items
  IconUsers,
  IconClipboardList,
  IconBook,
  IconCalendar,
  IconSchool,
  IconSettings,
  IconStethoscope,
  IconChartPie,
  IconBooks,
  IconCalendarEvent,
  IconBuilding,
  IconAdjustments,
  IconSchoolBell,
  IconFirstAidKit,
  IconPresentation,
};

export type IconName = keyof typeof iconMap; 